### ISSUE TITLE
Embed CSV table -> ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by danfowler** [errata-ai/markdata#2]
Great tool!  

Trying to embed a CSV table in a Markdown file (`table{'path': 'data/data.csv'}`), I get:

```
ValueError: I/O operation on closed file
```

I'm using Python 3.7.3 on macOS.

Wrapping `csv.DictReader(data)` in a `list()` [here](https://github.com/errata-ai/markdata/blob/master/markdata/directives.py#L42) seemed to work. 

See: https://stackoverflow.com/questions/55203713/python-valueerror-i-o-operation-on-closed-file-when-returning-a-dict-from-a-di

**Comment by jdkato** [comment]
This should be fixed in v0.4.1.
